name: biomass-spatial-cv
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - cudatoolkit=11.3  # Adjust based on your CUDA version
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - scipy>=1.7.0
  - rasterio>=1.2.0
  - geopandas>=0.10.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - tqdm>=4.62.0
  - pyyaml>=5.4.0
  - pillow>=8.3.0
  - jupyter>=1.0.0
  - pytest>=6.2.0
  - pip
  - pip:
    - plotly>=5.0.0
    - ipywidgets>=7.6.0
    - sphinx>=4.0.0
    - sphinx-rtd-theme>=0.5.0
    - black>=21.6.0
    - flake8>=3.9.0
    - isort>=5.9.0