preprocessing:
  chip_size: 24
  max_sat_nan_fraction: 0.3
  min_val_samples: 60
  min_valid_pixels: 0.7
  output_dir: results/preprocessing
  overlap: 0.1
  processed_dir: data/processed
  raster_pairs:
  - biomass_path: data/raw/biomass/yellapur_biomass.tif
    satellite_path: data/raw/satellite/yellapur_satellite.tif
    site_name: Yellapur
  - biomass_path: data/raw/biomass/betul_biomass.tif
    satellite_path: data/raw/satellite/betul_satellite.tif
    site_name: Betul
  - biomass_path: data/raw/biomass/achanakmar_biomass.tif
    satellite_path: data/raw/satellite/achanakmar_satellite.tif
    site_name: Achanakmar
  - biomass_path: data/raw/biomass/khaoyai_biomass.tif
    satellite_path: data/raw/satellite/khaoyai_satellite.tif
    site_name: Khaoyai
  - biomass_path: data/raw/biomass/uppangala_biomass.tif
    satellite_path: data/raw/satellite/uppangala_satellite.tif
    site_name: Uppangala
  test_ratio: 0.2
  use_log_transform: true
  val_ratio: 0.15
training:
  add_derived_features: true
  aug_probability: 0.7
  base_learning_rate: 0.001
  batch_size: 16
  create_ensemble: false
  cv_dir: results/cv_results
  early_stopping_patience: 20
  ensemble_method: average
  final_model_epochs: 150
  loss_function: huber
  model_type: cnn_coordinate
  n_folds: 5
  num_epochs: 100
  preprocessed_dir: data/processed
  results_dir: results/hybrid_results
  save_fold_models: true
  spatial_buffer: 20
  standardize_features: true
  train_final_model: true
  use_geometric_aug: true
  use_hard_negative_mining: true
  use_spectral_aug: true
  use_test_time_augmentation: true
  weight_decay: 0.005
