# Complete Pipeline Configuration
# This file combines preprocessing and training configurations

# preprocessing:
#   # Input raster pairs - UPDATE THESE PATHS WITH YOUR DATA
#   raster_pairs:
#     - satellite_path: "data/raw/satellite/s1_s2_l8_palsar_ch_dem_yellapur_2020.tif"
#       biomass_path: "data/raw/biomass/agbd_yellapur_reprojected_1.tif"
#       site_name: "Yellapur"
#     - satellite_path: "data/raw/satellite/s1_s2_l8_palsar_ch_betul_2020_clipped.tif"
#       biomass_path: "data/raw/biomass/01_Betul_AGB40_band1_onImgGrid.tif"
#       site_name: "Betul"
#     - satellite_path: "data/raw/satellite/s1_s2_l8_palsar_ch_goa_achankumar_2020_clipped.tif"
#       biomass_path: "data/raw/biomass/02_Achanakmar_AGB40_band1_onImgGrid.tif"
#       site_name: "Achanakmar"
#     - satellite_path: "data/raw/satellite/s1_s2_l8_palsar_ch_goa_khaoyai_2020_clipped.tif"
#       biomass_path: "data/raw/biomass/05_Khaoyai_AGB40_band1_onImgGrid.tif"
#       site_name: "Khaoyai"
#     - satellite_path: "data/raw/satellite/s1_s2_l8_palsar_ch_goa_uppangala_2020_clipped.tif"
#       biomass_path: "data/raw/biomass/04_Uppangala_AGB40_band1_onImgGrid.tif"
#       site_name: "Uppangala"
preprocessing:
  raster_pairs:
    - satellite_path: "/teamspace/studios/dl2/clean/data/s1_s2_l8_palsar_ch_dem_yellapur_2020.tif"
      biomass_path: "/teamspace/studios/dl2/clean/data/agbd_yellapur_reprojected_1.tif"
      site_name: "Yellapur"
    - satellite_path: "/teamspace/studios/dl2/clean/data/s1_s2_l8_palsar_ch_betul_2020_clipped.tif"
      biomass_path: "/teamspace/studios/dl2/clean/data/01_Betul_AGB40_band1_onImgGrid.tif"
      site_name: "Betul"
    - satellite_path: "/teamspace/studios/dl2/clean/data/s1_s2_l8_palsar_ch_goa_achankumar_2020_clipped.tif"
      biomass_path: "/teamspace/studios/dl2/clean/data/02_Achanakmar_AGB40_band1_onImgGrid.tif"
      site_name: "Achanakmar"
    - satellite_path: "/teamspace/studios/dl2/clean/data/s1_s2_l8_palsar_ch_goa_khaoyai_2020_clipped.tif"
      biomass_path: "/teamspace/studios/dl2/clean/data/05_Khaoyai_AGB40_band1_onImgGrid.tif"
      site_name: "Khaoyai"
    - satellite_path: "/teamspace/studios/dl2/clean/data/s1_s2_l8_palsar_ch_goa_uppangala_2020_clipped.tif"
      biomass_path: "/teamspace/studios/dl2/clean/data/04_Uppangala_AGB40_band1_onImgGrid.tif"
      site_name: "Uppangala"
  
  
  # Preprocessing parameters
  output_dir: "results/preprocessing"
  processed_dir: "data/processed"
  chip_size: 24
  overlap: 0.1
  use_log_transform: true
  min_valid_pixels: 0.7
  max_sat_nan_fraction: 0.3
  test_ratio: 0.2
  val_ratio: 0.15
  min_val_samples: 60

training:
  # Training parameters
  preprocessed_dir: "data/processed"
  results_dir: "results/hybrid_results"
  cv_dir: "results/cv_results"
  n_folds: 5
  spatial_buffer: 20
  model_type: "cnn_coordinate"
  
  # Model training
  batch_size: 16
  num_epochs: 100
  base_learning_rate: 0.001
  weight_decay: 0.005
  early_stopping_patience: 20
  
  # Advanced features
  add_derived_features: true
  standardize_features: true
  loss_function: "huber"
  use_hard_negative_mining: true
  use_test_time_augmentation: true
  use_geometric_aug: true
  use_spectral_aug: true
  aug_probability: 0.7