preprocessing:
  chip_size: 24
  max_sat_nan_fraction: 0.3
  min_val_samples: 60
  min_valid_pixels: 0.7
  output_dir: results/preprocessing
  overlap: 0.1
  processed_dir: data/processed
  raster_pairs:
  raster_pairs:
  - biomass_path: data/raw/biomass/yellapur_biomass.tif
    satellite_path: data/raw/satellite/yellapur_satellite.tif
    site_name: Yellapur
  - biomass_path: data/raw/biomass/betul_biomass.tif
    satellite_path: data/raw/satellite/betul_satellite.tif
    site_name: Betul
  - biomass_path: data/raw/biomass/achanakmar_biomass.tif
    satellite_path: data/raw/satellite/achanakmar_satellite.tif
    site_name: Achanakmar
  - biomass_path: data/raw/biomass/khaoyai_biomass.tif
    satellite_path: data/raw/satellite/khaoyai_satellite.tif
    site_name: Khaoyai
  - biomass_path: data/raw/biomass/uppangala_biomass.tif
    satellite_path: data/raw/satellite/uppangala_satellite.tif
    site_name: Uppangala
  test_ratio: 0.2
  use_log_transform: true
  val_ratio: 0.15
